### ISSUE TITLE
Integartion fails to start with HA 2023.11.0b0

### ISSUE THREAD

**Issue by luisiam** [Tasshack/dreame-vacuum#256]
**Describe the bug**
After upgrading to HA 2023.11.0b0, the integration fails to start. It still works on HA 2023.10.5.

**To Reproduce**
Upgrade to HA 2023.11.0b0

**Expected behavior**
The integration should be able to start after the upgrade.

**Screenshots**
N/A

**Additional Information (please complete the following information)**
 - Model Name [e.g. dreame.vacuum.p2028]: dreame.vacuum.r2228o
 - Firmware Version [e.g. 1156]: 1.3.3_2303
 - Home Assistant Version: 2023.11.0b0
 - Configuration Type [With or without map support]: With map support
 - Errors or warnings shown in the HA logs (if applicable):
```
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 2:13:35 PM (1 occurrences)
Last logged: 2:13:35 PM

Error setting up entry DreameBot L10s Ultra for dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/__init__.py", line 22, in async_setup_entry
    coordinator = DreameVacuumDataUpdateCoordinator(hass, entry=entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 125, in __init__
    persistent_notification.EVENT_PERSISTENT_NOTIFICATIONS_UPDATED,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.components.persistent_notification' has no attribute 'EVENT_PERSISTENT_NOTIFICATIONS_UPDATED'
```

**Comment by LukaszP2** [comment]
Same to me

**Comment by jlpouffier** [comment]
Same to me too ;)

**Comment by tteck** [comment]
Use beta

**Comment by luisiam** [comment]
v2.0.0b6 is working. When will the "official" version be released? HA 2023.11.0 will be releasing on Wed (11/1)

**Comment by Sompse** [comment]
I have same or similar issue with v2.0.0b6,   Error seems to point not able to get device from cloud, so this could be issue also on Dreame cloud side??

Home Assistant 2023.10.5
Supervisor 2023.10.1
Operating System 11.1

Logger: custom_components.dreame_vacuum
Source: custom_components/dreame_vacuum/coordinator.py:476
Integration: Dreame Vacuum (documentation, issues)
First occurred: 28. lokakuuta 2023 klo 17.30.55 (693 occurrences)
Last logged: 09.17.43

Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 471, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1990, in update self.connect_device() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1518, in connect_device self._request_properties() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 459, in _request_properties result = self._protocol.get_properties(props[:15]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1265, in get_properties return self.send( ^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/protocol.py", line 1253, in send raise DeviceException( custom_components.dreame_vacuum.dreame.exceptions.DeviceException: Unable to discover the device over cloud

**Comment by supergroover** [comment]
Same problem in version 2023.11.0

**Comment by gresnyer** [comment]
Same issue after installing official 2023.11.0:

"2023-11-01 21:08:05.594 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Dreame Bot L10 Pro for dreame_vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/__init__.py", line 22, in async_setup_entry
    coordinator = DreameVacuumDataUpdateCoordinator(hass, entry=entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreame_vacuum/coordinator.py", line 125, in __init__
    persistent_notification.EVENT_PERSISTENT_NOTIFICATIONS_UPDATED,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.components.persistent_notification' has no attribute 'EVENT_PERSISTENT_NOTIFICATIONS_UPDATED'
2023-11-01 21:08:05.645 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: dreame_vacuum"

**Comment by lotr** [comment]
guys, all you need to do is to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED in the /config/custom_components/dreame_vacuum/coordinator.py 

I found it was rename in the HA

**Comment by gresnyer** [comment]
> guys, all you need to do is to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED in the /config/custom_components/dreame_vacuum/coordinator.py
> 
> I found it was rename in the HA

Confirmed, working with this change.

**Comment by Maddman268** [comment]
works, thanks for this hind

**Comment by oekinger** [comment]
> I encourage everyone to switch to the Beta version.
> 
> https://hacs.xyz/docs/faq/beta/

Works perfectly. Thanks for this advice!

**Comment by adrien0595** [comment]
> guys, all you need to do is to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED in the /config/custom_components/dreame_vacuum/coordinator.py
> 
> I found it was rename in the HA

Thanks ! 👍

**Comment by CannyGent** [comment]
> guys, all you need to do is to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED in the /config/custom_components/dreame_vacuum/coordinator.py

This worked for me too. Remember to restart HASS to pick up the change.

**Comment by danieljowitsch** [comment]
Stopped working for me too.

**Comment by pophitru** [comment]
> guys, all you need to do is to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED in the /config/custom_components/dreame_vacuum/coordinator.py
> 
> I found it was rename in the HA

THANK YOU! worked like a charm

**Comment by MatDelaz** [comment]
thx a lot :D

**Comment by swausb** [comment]
> guys, all you need to do is to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED in the /config/custom_components/dreame_vacuum/coordinator.py
> 
> I found it was rename in the HA

Does not work for me.. I'm already using the beta version and changed the coordinator.py but it's still not working

**Comment by swausb** [comment]
Which logs do you need? The setup fails for me since HA 2023.11

**Comment by swausb** [comment]
Ahh found the problem myself and fixed it.. it's working now :) Thanks for helping!

**Comment by conrad-roux** [comment]
> Ahh found the problem myself and fixed it.. it's working now :) Thanks for helping!

Would you mind to mention what it was? This is not helpful for other people referencing this issue.

**Comment by swausb** [comment]
I didn't do it because I simply had to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED as described above and just forgot to restart. I was a bit embarrassed xD

**Comment by danieljowitsch** [comment]
> I didn't do it because I simply had to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED as described above and just forgot to restart. I was a bit embarrassed xD

We’ve all been there. I was about to post similar but then luckily remembered that I should try to restart which made it work for me. Glad it’s working for you now.

**Comment by Bagunda** [comment]
> all you need to do is to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED in the /config/custom_components/dreame_vacuum/coordinator.py
Same problem. Core 2023.11.2 Supervisor 2023.11.0.

Rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED helped

**Comment by sephrioth** [comment]
I got a new error in HA 2023.11, it  has caused the integration to fail to launch.

`Integration start failed: Traceback (most recent call last): File "/config/custom_components/dreame_vacuum/coordinator.py", line 471, in _async_update_data await self.hass.async_add_executor_job(self._device.update) File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1990, in update self.connect_device() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 1518, in connect_device self._request_properties() File "/config/custom_components/dreame_vacuum/dreame/device.py", line 464, in _request_properties return self._handle_properties(results) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/dreame_vacuum/dreame/device.py", line 431, in _handle_properties callback[0](callback[1]) File "/config/custom_components/dreame_vacuum/coordinator.py", line 282, in _low_water_warning_changed {EVENT_LOW_WATER: description[0], "code": low_water_warning.value}, ^^^^^^^^^^^ UnboundLocalError: cannot access local variable 'description' where it is not associated with a value`

**Comment by PFly61** [comment]
_guys, all you need to do is to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED in the /config/custom_components/dreame_vacuum/coordinator.py_
GRAZIE ! risolto anche per me

**Comment by Kr0men** [comment]
> guys, all you need to do is to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED in the /config/custom_components/dreame_vacuum/coordinator.py
> 
> I found it was rename in the HA

It works like a charm ! Thank you

**Comment by bp-ouhaha** [comment]
working for me too after upgrade to Beta version.

(otherwise "Failed to set up"

**Comment by mojrs10** [comment]
> guys, all you need to do is to rename EVENT_PERSISTENT_NOTIFICATIONS_UPDATED to SIGNAL_PERSISTENT_NOTIFICATIONS_UPDATED in the /config/custom_components/dreame_vacuum/coordinator.py
> 
> I found it was rename in the HA

Thanks!
